# Generated by Django 2.0.1 on 2018-02-27 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_submission',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
