# Generated by Django 2.0.1 on 2018-02-01 23:05

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20180201_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['date', 'name']},
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(default='123', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='grader',
            field=models.FileField(null='true', upload_to=archive.models.grader_dir),
        ),
    ]
