# Generated by Django 2.0.1 on 2018-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_profile_last_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hidden',
            field=models.BooleanField(default='False'),
        ),
    ]
