# Generated by Django 2.0.1 on 2018-03-22 10:27

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_problem_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='judge',
            field=models.FileField(blank=True, default=None, null=True, upload_to=archive.models.judge_dir),
        ),
        migrations.AddField(
            model_name='problem',
            name='no_io',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
