# Generated by Django 2.0.1 on 2018-02-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20180201_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
