# Generated by Django 2.0.1 on 2018-02-08 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20180205_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
