# Generated by Django 2.0.1 on 2018-02-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20180208_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('file', models.FileField(upload_to='comparators/')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='comparator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Comparator'),
        ),
    ]
