# Generated by Django 2.0.1 on 2018-02-10 13:30

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20180210_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.FileField(null=True, upload_to=archive.models.solution_dir),
        ),
    ]
