# Generated by Django 2.0.1 on 2018-02-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_problem_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('EE', 'Evaluation Error'), ('RNG', 'Running...')], default='RNG', max_length=5),
        ),
    ]
