# Generated by Django 2.0.1 on 2018-02-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20180210_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template',
            field=models.TextField(default=''),
        ),
    ]
