# Generated by Django 2.0.1 on 2018-02-11 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20180211_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
